<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b85f068b-34e9-4443-b25b-6c92fe3d333a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="TypeGen" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Parley\Parley.csproj" />
  </ItemGroup>

  <Target Name="RunTypeGen" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
	<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet-typegen generate -c  typegen.json" />
  </Target>

</Project>
